### ISSUE TITLE
TODO vue componenten

### ISSUE THREAD

**Issue by jbvilla** [SELab-2/Dr-Trottoir-5#95]
- [x] #114
![image](https://user-images.githubusercontent.com/79803080/227546655-44dd2500-40a4-421b-b178-d9175eac6ea9.png)

- [x] #119
![image](https://user-images.githubusercontent.com/79803080/227547090-04008a45-042b-40ef-b5b6-e59de40d4bf5.png)

- [x] #97
![image](https://user-images.githubusercontent.com/79803080/227549450-b2bea2b5-97ba-441e-8a25-1eef36c9e79e.png)

- [x] Syndicus kaart (kan meerderen gebouwen hebben)
![image](https://user-images.githubusercontent.com/79803080/227549855-34e6dda0-7394-4fa9-921f-57b159078014.png)

- [x] #121
![image](https://user-images.githubusercontent.com/79803080/227550802-60fd0c26-c820-4776-95d9-5428397a1cb2.png)
Mail knop voor superstudent en admin:
![image](https://user-images.githubusercontent.com/79803080/227550880-dccf90b9-5485-4db4-ae22-af5ba3233133.png)

- [x] Superstudent en admin #118
![image](https://user-images.githubusercontent.com/79803080/227552815-7956c0fe-5a8b-443e-aa1d-151b6ec33165.png)
![image](https://user-images.githubusercontent.com/79803080/227552921-0ef09c68-5655-43a1-ab8e-ccc0dfc12c62.png)
![image](https://user-images.githubusercontent.com/79803080/227553016-8203adf8-f0e5-498c-9f78-375e6af74354.png)

- [x] student dagplanning (misschien nieuw design nodig)
![image](https://user-images.githubusercontent.com/79803080/227555032-0b57bb59-7b5b-4e6f-8991-87e4f9d3b400.png)

- [x] pop-up als je geregistreerd hebt TODO moet veralgemeend worden
![image](https://user-images.githubusercontent.com/79803080/227556243-a9429104-eaaa-4323-9b9c-a52ad747b7e0.png)
![image](https://user-images.githubusercontent.com/79803080/227556391-2bd9a0cb-f14c-4b20-8781-2dae3a51af4b.png)
